### ISSUE TITLE
Add how to add an new MIB path into the documentation

### ISSUE THREAD

**Issue by robertcheramy** [vincentbernat/snimpy#102]
If you add new MIBs to your system, say cisco MIBs with snmp-mibs-downloader (debian), you have to tell snimpy where to find them (/var/lib/mibs/cisco).
Using /etc/snmp.conf does not work, as snimpy uses libsmi, so you have to add the path to /etc/smi.conf or $HOME/.smirc, as documented in man smi_config.

It would be very useful to add this information in the documentation of snimpy, because it is not easy for a user to find this out.

**Comment by vincentbernat** [comment]
Please, do a pull request to suggest an update of the documentation.
