### ISSUE TITLE
Cross-compile snimpy

### ISSUE THREAD

**Issue by midicase** [vincentbernat/snimpy#21]
Trying to cross compile but having issues with cffi.  Scenario (buildroot style):
Host (not distro) python is built and installed in a host folder struct.
Host python builds native python which is installed in a staging folder.
Host python can build and install python modules that are installed in "host" and/or staging depending if they are needed for other modules (in this case cffi and pycparser to satisfy snimpy prereqs).

I can build snimpy cffi module as either host mode or cross mode,  but host mode, which succeeds, is not useful for the target and cross mode fails to build since it wants to load the module (which I can't, different architecture).

I did see someone else had the same issue on a different project (I see you were involved), but I was not able to determine what the solution was.   Similarly the target system does not have a compiler.

Is there a way to generate snimpy's cffi so file in a cross build system or is it locked into a coupled build-and-load compile?

**Comment by midicase** [comment]
Followup, this mentions cross-compiling, but I can't quite follow if it is intended to be used for cross
https://caremad.io/2014/11/distributing-a-cffi-project/

**Comment by vincentbernat** [comment]
When you say that cross mode fails to build, what trace do you get?

**Comment by midicase** [comment]
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    import snimpy.mib
  File "/home/mike/workspace/buildroot/output/build/python-snimpy-0.8.3/snimpy/mib.py", line 155, in <module>
    """, libraries=["smi"])
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/cffi/api.py", line 340, in verify
    lib = self.verifier.load_library()
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/cffi/verifier.py", line 75, in load_library
    return self._load_library()
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/cffi/verifier.py", line 151, in _load_library
    return self._vengine.load_library()
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/cffi/vengine_cpy.py", line 149, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/home/mike/workspace/buildroot/output/build/python-snimpy-0.8.3/snimpy/__pycache__/_cffi__x3a5e05ccxa0dd8598.so': /home/mike/workspace/buildroot/output/build/python-snimpy-0.8.3/snimpy/__pycache__/_cffi__x3a5e05ccxa0dd8598.so: wrong ELF class: ELFCLASS32
make: *** [/home/mike/workspace/buildroot/output/build/python-snimpy-0.8.3/.stamp_built] Error 1


 $ file python-snimpy-0.8.3/snimpy/__pycache__/_cffi__x3a5e05ccxa0dd8598.so 
python-snimpy-0.8.3/snimpy/__pycache__/_cffi__x3a5e05ccxa0dd8598.so: ELF 32-bit LSB shared object, ARM, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x699a20b992f6e0b2d246aed5c42a7b4c0039926e, not stripped

**Comment by midicase** [comment]
Someone seems to have found a work around:
https://github.com/pyca/cryptography/issues/1325
dstufft implementation:
github.com/dstufft/http11/blob/master/src/http11/c/__init__.py#L102-L156
Looks to be based on this:
https://caremad.io/2014/11/distributing-a-cffi-project/

**Comment by midicase** [comment]
Sorry, I failed to mention I was using the last tagged release 0.8.3.  Browsing the commits since then I see some changes that may deal with this.  Trying master now.

**Comment by vincentbernat** [comment]
I did not implement the whole changes suggested by Donald but I just did. You can try again with master.

**Comment by vincentbernat** [comment]
I just pushed more changes. This shouldn't affect you but if you already tested, please test again. This would allow me to push a release.

**Comment by midicase** [comment]
Using 58fbdf15fe27d671e98c7bd2b9f06eed87369bcd

I run the build twice, once for host and it creates host install OK:
 file buildroot/output/host/usr/lib/python2.7/site-packages/snimpy-0.8.3-py2.7-linux-x86_64.egg/_Mib_cffi_adfc5903x8ee9bbc1.so 
buildroot/output/host/usr/lib/python2.7/site-packages/snimpy-0.8.3-py2.7-linux-x86_64.egg/_Mib_cffi_adfc5903x8ee9bbc1.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0xbd2d2787f06990858bb99e0d187d773522afb149, not stripped

Then cross-build generates the correct cffi backend, but it seems the install tries load the cross built file:

(cd /home/mike/workspace/buildroot/output/build/python-snimpy-undefined; /home/mike/workspace/buildroot/output/host/usr/bin/python setup.py build)
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/snimpy
copying snimpy/basictypes.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/snmp.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/__init__.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/manager.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/mib.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/__main__.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/main.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/smi.py -> build/lib.linux-x86_64-2.7/snimpy
copying snimpy/config.py -> build/lib.linux-x86_64-2.7/snimpy
running build_ext
building '_Mib_cffi_adfc5903x8ee9bbc1' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/snimpy
creating build/temp.linux-x86_64-2.7/snimpy/__pycache__
/home/mike/workspace/buildroot/output/host/usr/bin/ccache /usr/bin/gcc -pthread -fno-strict-aliasing -O2 -I/home/mike/workspace/buildroot/output/host/usr/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mike/workspace/buildroot/output/host/usr/include/python2.7 -c snimpy/__pycache__/_Mib_cffi_adfc5903x8ee9bbc1.c -o build/temp.linux-x86_64-2.7/snimpy/__pycache__/_Mib_cffi_adfc5903x8ee9bbc1.o
/home/mike/workspace/buildroot/output/host/usr/bin/ccache /usr/bin/gcc -pthread -shared -L/home/mike/workspace/buildroot/output/host/lib -L/home/mike/workspace/buildroot/output/host/usr/lib -Wl,-rpath,/home/mike/workspace/buildroot/output/host/usr/lib build/temp.linux-x86_64-2.7/snimpy/__pycache__/_Mib_cffi_adfc5903x8ee9bbc1.o -L/home/mike/workspace/buildroot/output/host/usr/lib -lsmi -lpython2.7 -o build/lib.linux-x86_64-2.7/_Mib_cffi_adfc5903x8ee9bbc1.so
>>> python-snimpy undefined Installing to target
(cd /home/mike/workspace/buildroot/output/build/python-snimpy-undefined; PYTHONPATH=/home/mike/workspace/buildroot/output/target/usr/lib/python2.7/site-packages /home/mike/workspace/buildroot/output/host/usr/bin/python setup.py install --prefix=/home/mike/workspace/buildroot/output/target/usr)
running install
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    "install": SnimpyInstallCommand,
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 32, in finalize_options
    self.distribution.ext_modules = get_cffi_modules()
  File "setup.py", line 20, in get_cffi_modules
    import snimpy.smi
  File "/home/mike/workspace/buildroot/output/build/python-snimpy-undefined/snimpy/smi.py", line 185, in <module>
    ffi = FFI()
  File "/home/mike/workspace/buildroot/output/target/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: /home/mike/workspace/buildroot/output/target/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/_cffi_backend.so: wrong ELF class: ELFCLASS32
make: *** [/home/mike/workspace/buildroot/output/build/python-snimpy-undefined/.stamp_target_installed] Error 1

$ file /home/mike/workspace/buildroot/output/target/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/_cffi_backend.so
/home/mike/workspace/buildroot/output/target/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/_cffi_backend.so: ELF 32-bit LSB shared object, ARM, version 1 (SYSV), dynamically linked, BuildID[sha1]=0xc24fd1452d57958ec79c41ef65a73ef0d7588590, stripped

**Comment by vincentbernat** [comment]
Do you think that having `x86_64` everywhere while compiling is expected? The error seems that CFFI has not been crosscompiled. Has it?

**Comment by vincentbernat** [comment]
Well, no, CFFI was cross-compiled, hence the error. Could you try with https://github.com/dstufft/http11/?

**Comment by vincentbernat** [comment]
Or maybe https://github.com/pyca/bcrypt/ which has a solved issue about cross-compilation: https://github.com/pyca/bcrypt/issues/34 (but I think I am doing the exact same thing as them).

**Comment by midicase** [comment]
x86_64 is an artifact of the cross compile.  The host plat gets picked up and suffixed on to the info but does not affect.  

cffi is host and cross built:
Host:
$file buildroot/output/host/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/_cffi_backend.so 
_cffi_backend.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0x957b6d240264c35deaa1dd07c6d95e112310ef7c, not stripped

Cross:
 $ file buildroot/output/target/usr/lib/python2.7/site-packages/cffi-0.8.6-py2.7-linux-x86_64.egg/_cffi_backend.so 
_cffi_backend.so: ELF 32-bit LSB shared object, ARM, version 1 (SYSV), dynamically linked, BuildID[sha1]=0xc24fd1452d57958ec79c41ef65a73ef0d7588590, stripped

Is there a way to get install to load the host cffi?  Trying http11 now.

**Comment by vincentbernat** [comment]
In the bug report for bcrypt, they say this works if you have CFFI installed on the host. You seem to say that this is already the case for you. On the host, does `from cffi import FFI` and `FFI()` works from the host python?

**Comment by midicase** [comment]
$ PYTHONPATH=/home/mike/workspace/buildroot/output/host/usr/lib/python2.7/site-packages /home/mike/workspace/buildroot/output/host/usr/bin/python
Python 2.7.3 (default, Feb  1 2015, 09:35:34) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cffi import FFI
>>> FFI()
<cffi.api.FFI object at 0x7f6bd0059990>

Getting same install issue with bcrypt and http11.  I can't find examples of those being cross compiled.  That may provide some insight on how to load ext module that does not conflict with PYTHONPATH usage.

**Comment by midicase** [comment]
I found it.   Should not cross-compile cffi and install in target.   Removed cross cffi, then the import falls back to the host python path and picks up the proper module.

**Comment by vincentbernat** [comment]
Great! So, it now works "out of the box"?

**Comment by midicase** [comment]
Cross building looks like it will have to go like this:
build and install host cffi
build and install target packages that depend in cffi
build and install target cffi

It will just mean splitting out the cross build system's cffi handling into two packages and create a chain of dependencies between them.

**Comment by midicase** [comment]
Thanks!   Loads on ARM!
```python
[root@t21 ~]# python
Python 2.7.3 (default, Feb  1 2015, 04:34:21) 
[GCC 4.7.3 20121106 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from snimpy.manager import Manager as M
>>> 
```
