### ISSUE TITLE
SmiObject.conformance always returns 1

### ISSUE THREAD

**Issue by midicase** [vincentbernat/snimpy#23]
Hi again.

Already have snmpd running and can query:

```
[root@t21 ~]# snmpwalk -m+SNMPv2-MIB -c public localhost sysDescr.0
SNMPv2-MIB::sysDescr.0 = STRING: Linux t21 3.10.12 #1 SMP Thu Oct 23 11:15:42 EDT 2014 armv7l
```
Trying an example script:

```python
from snimpy.manager import Manager as M
from snimpy.manager import load

load("/usr/share/snmp/mibs/SNMPv2-MIB")
m = M("localhost", "public", 2)
print(m.sysDescr)
```
Would always return this:

```python
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    load("/usr/share/snmp/mibs//SNMPv2-MIB")
  File "/usr/lib/python2.7/site-packages/snimpy-0.8.4-py2.7-linux-x86_64.egg/snimpy/manager.py", line 435, in load
    m = mib.load(mibname)
  File "/usr/lib/python2.7/site-packages/snimpy-0.8.4-py2.7-linux-x86_64.egg/snimpy/mib.py", line 550, in load
    "(check with smilint -s -l1)".format(mib))
snimpy.mib.SMIException: /usr/share/snmp/mibs/IF-MIB.txt contains major SMI error (check with smilint -s -l1)
```
Tried with other well know mibs and verified that the MIB is OK:

```
$ smilint -l1 -s SNMPv2-MIB
$ echo $?
0
```

Seems that the SmiObject.conformance was returning 1:

```python
-> if m.conformance and m.conformance <= 1:
(Pdb) print ffi
<cffi.api.FFI object at 0x17360f0>
(Pdb) print m.conformance
1
(Pdb) print m
<cdata 'SmiModule *' 0x1580368>
```

So I thought I would just bypass that error to see what happens 
```python
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(m.sysDescr)
  File "/usr/lib/python2.7/site-packages/snimpy-0.8.4-py2.7-linux-x86_64.egg/snimpy/manager.py", line 269, in __getattribute__
    oid, result = self._session.get(a.oid + (0,))[0]
  File "/usr/lib/python2.7/site-packages/snimpy-0.8.4-py2.7-linux-x86_64.egg/snimpy/snmp.py", line 256, in get
    return self._op(self._cmdgen.getCmd, *oids)
  File "/usr/lib/python2.7/site-packages/snimpy-0.8.4-py2.7-linux-x86_64.egg/snimpy/snmp.py", line 248, in _op
    return tuple([(oid, self._convert(val)) for oid, val in results])
  File "/usr/lib/python2.7/site-packages/snimpy-0.8.4-py2.7-linux-x86_64.egg/snimpy/snmp.py", line 220, in _convert
    self._check_exception(value)
  File "/usr/lib/python2.7/site-packages/snimpy-0.8.4-py2.7-linux-x86_64.egg/snimpy/snmp.py", line 198, in _check_exception
    raise SNMPNoSuchObject("No such object was found")  # nopep8
snimpy.snmp.SNMPNoSuchObject: No such object was found
```

Running snmpd is debug mode and spotted me this:
```
ccitt.1.1.0 = No Such Object available on this agent at this OID
```
 Maybe something to do with the way my library stack is used.

So I was suspecting an issue in the underlying oid look up, so I figure I'd try to bypass with my rusty python skills:

```python
from snimpy import snmp
s = snmp.Session("localhost", "public", 2)
r = s.get("1.3.6.1.2.1.1.1.0")
r.print

((1, 3, 6, 1, 2, 1, 1, 1, 0), 'Linux t21 3.10.12 #1 SMP Thu Oct 23 11:15:42 EDT 2014 armv7l')
```

Yay!  A response.  I can live with that if I have too, but a web developer will hate it.

I don't mind debugging this out a bit further out myself, but not sure what to start to tackle:
1.  libffi 
2.  cffi 
3.  cffi double build, host + target, and snimpy build with one but run-time on the other
4.  What the heck is ccitt?  

Thanks

**Comment by vincentbernat** [comment]
Could you bypass the check and check the OID you get with `mib.get(m, "sysDescr").oid`?

If the OID is quite incorrect, I suspect that CFFI didn't understand your target during cross-compilation.

**Comment by midicase** [comment]
mib.get(m, "sysDescr").oid
```python
*** AttributeError: '_cffi_backend.CData' object has no attribute 'encode'
```

Reviewing my cross-compile environment.

**Comment by vincentbernat** [comment]
Sorry, I did give you the wrong command. Try `mib.get("SNMPv2-MIB", "sysDescr").oid`.

**Comment by midicase** [comment]
Can I run that like this?  Changed the conformace test to "< 1" so 1 passes:
```python
>>> from snimpy import mib
>>> oid = mib.get("/usr/share/snmp/mibs/SNMPv2-MIB", "sysDescr").oid
>>> print oid
(0L, 1L, 1L)
```

**Comment by vincentbernat** [comment]
You can try snimpy 0.6.4. It still uses libsmi but it uses a classic Python module instead of CFFI. If it works, the problem is likely with CFFI. I would have expected the OID to be something with very high numbers or that you would get segfaults.

Could you try:

```
import snimpy.mib
from snimpy.smi import smi, ffi
a=smi.smiGetModule("SNMPv2-MIB")
print ffi.string(a.name)
c=smi.smiGetNode(a, "sysDescr")
print ffi.string(c.name)
print c.oidlen
print [x for x in c.oid[0:c.oidlen]]
```

**Comment by midicase** [comment]
```python
>>> import snimpy.mib
>>> from snimpy.smi import smi, ffi
>>> a=smi.smiGetModule("/usr/share/snmp/mibs/SNMPv2-MIB")
>>> print ffi.string(a.name)
SNMPv2-MIB
>>> c=smi.smiGetNode(a, "sysDescr")
>>> print ffi.string(c.name)
sysDescr
>>> print c.oidlen
3
>>> print [x for x in c.oid[0:c.oidlen]]
[0L, 1L, 1L]
```

I noticed that I have to put the fully qualified path to load, but since some mibs have IMPORTS, how does snimpy (or rather libsmi) resolve?  

I tried running in the mibs directory
[root@t21 mibs]# pwd
/usr/share/snmp/mibs
[root@t21 mibs]# python
```python
Python 2.7.3 (default, Feb  1 2015, 04:34:21) 
[GCC 4.7.3 20121106 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import snimpy.mib
>>> from snimpy.smi import smi, ffi
>>> a=smi.smiGetModule("SNMPv2-MIB")
>>> print ffi.string(a.name)
Segmentation fault
```

**Comment by vincentbernat** [comment]
Oh, yes, maybe libsmi is not configured correctly. It reads a configuration file (`/etc/smi.conf` for example). There is a default search path and you can add more in `/etc/smi.conf`. You could add:

```
path :/usr/share/snmp/mibs
```

For loading dependencies, libsmi will try to load them automatically.

**Comment by vincentbernat** [comment]
However, as far as I know, `smilint` should work exactly the same.

**Comment by vincentbernat** [comment]
If it helps, I have just pushed a commit that should display the error that libsmi detected. For example:

```
SMIException: /home/bernat/Documents/Deezer/MIB/allied/ATSWTCH2-MIB contains major SMI error (/home/bernat/Documents/Deezer/MIB/allied/ATSWTCH2-MIB:47: failed to locate MIB module `RFC-1212': check with smilint -s -l1)
```

**Comment by midicase** [comment]
```
path :/usr/share/snmp/mibs
```
smi.conf is the fix.  Thank you! I feel bad since it was not an issue with snimpy.   libsmi does not include or install an smi.conf.  Distro handlers seem to be manually doing it.  I'll add it to buildroot.


```python
>>> from snimpy.manager import Manager as M
>>> from snimpy.manager import load
>>> load("SNMPv2-MIB")
>>> m = M("localhost", "public", 2)
>>> print(m.sysDescr)
Linux t21 3.10.12 #1 SMP Thu Oct 23 11:15:42 EDT 2014 armv7l
```

**Comment by vincentbernat** [comment]
OK, that's odd that smilint worked without it. Looking at the source code, there is no hard coded path in smilint.

**Comment by midicase** [comment]
Used smilint on the desktop.  Never used smilint/libsmi on target platforms.
