### ISSUE TITLE
Docs (readthedocs) with some problems

### ISSUE THREAD

**Issue by rarylson** [vincentbernat/snimpy#26]
The docs from snimpy are with errors in the API reference:

- https://snimpy.readthedocs.org/en/latest/api.html

As a workarround, users can use the docs from snimpy 0.8.0:

- https://snimpy.readthedocs.org/en/0.8.0/api.html

However, the problem doesn't exist if the docs are generated in a development env using `make docs`. All the docs are correctly generated.

May be was interesting to generate new docs and uploading them to the readthedocs.

PS: Thanks for the project!

**Comment by vincentbernat** [comment]
Read the Docs automatically build the documentation. I don't think I can upload previous versions easily.
