### ISSUE TITLE
Crash in _toBytes()

### ISSUE THREAD

**Issue by mhite** [vincentbernat/snimpy#27]
I'm seeing the following exception when accessing an SNMP OID SNMPv2-SMI::enterprises.23022.2.50.1.1.3.1.2.0:

ValueError: u'ila_040106_010815\n' cannot be parsed because it does not match format 255a at index 17

snmp value in question looks like this in the output of snmpwalk:

SNMPv2-SMI::enterprises.23022.2.50.1.1.3.1.2.0 = STRING: "ila_040105_070213
"
(This is a NetOptics inline tap, LA-2407)

It sounds like the parser chokes on the newline when converting? (No real idea, it's just a guess.)

I'm running snimpy==0.8.4.

**Comment by vincentbernat** [comment]
Good catch. I just pushed a commit to fix that.

**Comment by mhite** [comment]
Thanks -- vendor-specific OIDs are full of all sorts of nonsense. ;) Thank you for fixing.

**Comment by mhite** [comment]
Also, I've tested the fix and it works! (But you knew that.)

**Comment by vincentbernat** [comment]
❦  3 avril 2015 13:22 -0700, Matt Hite <notifications@github.com> :

> Also, I've tested the fix and it works! (But you knew that.)

Thanks for testing. I have pushed a new release with this fix.
-- 
Use self-identifying input.  Allow defaults.  Echo both on output.
            - The Elements of Programming Style (Kernighan & Plauger)
