### ISSUE TITLE
Add SNMPv3 support

### ISSUE THREAD

**Issue by vincentbernat** [vincentbernat/snimpy#3]
Currently, only SNMPv1 and SNMPv2c are supported.

**Comment by aakruthigopisetty** [comment]
So, can I now use this tool for SNMPv3? Could you send me some links or examples of its usage for snmp version 3? Eagerly awaiting your response.

**Comment by vincentbernat** [comment]
For example:

    m = M(version=3,
          secname="readonly",
          authprotocol="MD5", authpassword="authpass",
          privprotocol="AES", privpassword="privpass")

**Comment by aakruthigopisetty** [comment]
Thank you so much !! Could you point me to some wholly written scripts that use this tool for snmpv3?

**Comment by vincentbernat** [comment]
See in the `examples/` directory. Just replace community-authentication with a v3 authentication like above.

**Comment by aakruthigopisetty** [comment]
Hey,

Thank you so much for your very prompt replies!

I need to do the following, with your tool:

1. Query the device for scalar oids and tabular oids and get the response
2. Once the response is received, I need to store it in a format (json,
xml, etc)
3. Compare this output/response with an 'expected output' (same format as
generated output)
4. Generate an error report as against a rule set defined.

Can all of this be done using your tool? If so, could you please guide me
through it?

I'd really be grateful to you if you could help me out with this.

Looking forward to your reply.

Thanks,
Aakruthi

**Comment by vincentbernat** [comment]
Snimpy doesn't allow to query directly OID. You need to use MIB names. Steps 2 to 4 are unrelated to Snimpy, you need to code them directly in Python.

**Comment by aakruthigopisetty** [comment]
Could you post some pseudo code for me to work on?

**Comment by vincentbernat** [comment]
The snimpy part is just `m.ifDescr[3]` (for example). All the remaining is plain Python. I can develop a whole compliance tool for you.

**Comment by aakruthigopisetty** [comment]
Oh ! That would be great, Vincent!

**Comment by vincentbernat** [comment]
Sorry, I meant I can't. I have too many things to do on my own. What you want is not complex, but it seems that you don't know Python. Find someone with some Python knowledge and some time and that should be pretty straightforward.

**Comment by aakruthigopisetty** [comment]
Yes! I am in the process of learning Python! But, if you could guide me
through it, it would help.

**Comment by aakruthigopisetty** [comment]
How do you query a table? For example, the IfTable or the entPhysicalTable?

**Comment by vincentbernat** [comment]
You don't, you can only query specific rows. Like `m.ifDescr[2]`. There is an example in the frontpage of the documentation: http://snimpy.readthedocs.org/en/latest/.

**Comment by aakruthigopisetty** [comment]
Thanks for all the help! Another question, for a v3 client, the parameters
I need to input are host, version, authprotocol, username and password.

There doesn't seem to be a field for the username. It would really help if
you could tell me how to input the username and password parameters to
connect to my v3 host.

Thanks,
Aakruthi

**Comment by vincentbernat** [comment]
`secname` is a username.
