### ISSUE TITLE
More OIDs returned when calling walk on snmp.Session

### ISSUE THREAD

**Issue by urban-1** [vincentbernat/snimpy#31]
Hi all,

I try to call walk directly on a Session instance. The data returned do start at the correct point/OID, however there are extra OIDs at the end. I suspect I am doing something wrong when calling it. Minimal example:

``` python
#!/usr/bin/env python

import argparse
from snimpy.snmp import Session as S

parser = argparse.ArgumentParser()
parser.add_argument("host", default="localhost", nargs="?",
                    help="Agent to retrieve variables from")
parser.add_argument("community", default="public", nargs="?",
                    help="Community to query the agent")
options = parser.parse_args()

s = S(options.host, options.community, 2)

res = s.walk((1,3,6,1,2,1,2,2,1))
for r in res:
    oid = ".".join(str(v) for v in r[0])
    print(oid)
```

The output is:
```
1.3.6.1.2.1.2.2.1.1.1
1.3.6.1.2.1.2.2.1.1.2
1.3.6.1.2.1.2.2.1.1.3
1.3.6.1.2.1.2.2.1.2.1
1.3.6.1.2.1.2.2.1.2.2
...
1.3.6.1.2.1.2.2.1.22.3
1.3.6.1.2.1.3.1.1.1.2.1.192.168.2.25
1.3.6.1.2.1.3.1.1.1.2.1.192.168.2.61
1.3.6.1.2.1.3.1.1.1.2.1.192.168.2.253
1.3.6.1.2.1.3.1.1.1.3.1.192.168.4.2
1.3.6.1.2.1.3.1.1.2.2.1.192.168.2.25
1.3.6.1.2.1.3.1.1.2.2.1.192.168.2.61
1.3.6.1.2.1.3.1.1.2.2.1.192.168.2.253
1.3.6.1.2.1.3.1.1.2.3.1.192.168.4.2
1.3.6.1.2.1.3.1.1.3.2.1.192.168.2.25
1.3.6.1.2.1.3.1.1.3.2.1.192.168.2.61
1.3.6.1.2.1.3.1.1.3.2.1.192.168.2.253
1.3.6.1.2.1.3.1.1.3.3.1.192.168.4.2
1.3.6.1.2.1.4.1.0
1.3.6.1.2.1.4.2.0
```

Shouldn't it stop at 1.3.6.1.2.1.2.2.1.22.3? Why am I getting the extra ones? I also tried the walk using a string instead of a tuple... same output. Any help would be appreciated.

Thanks,

Andreas

**Comment by vincentbernat** [comment]
❦ 17 mai 2015 14:11 -0700, Andreas Bontozoglou <notifications@github.com> :

> I try to call walk directly on a Session instance. The data returned
> do start at the correct point/OID, however there are extra OIDs at the
> end. I suspect I am doing something wrong when calling it. Minimal
> example:

No, that's expected. We receive more OID that we need when walking and
they should be discarded. This is done at the higher level within the
manager.

> Shouldn't it stop at 1.3.6.1.2.1.2.2.1.22.3? Why am I getting the
> extra ones? I also tried the walk using a string instead of a tuple...
> same output. Any help would be appreciated.

Walk requests are translated to GETBULK. We ask for the 10 next
OID. SNMP doesn't restrict this operation to a subtree (because it
wouldn't know which subtree it is). The client has to filter itself.
-- 
Write clearly - don't be too clever.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by urban-1** [comment]
Hmm... I will write a wrapper function for this then. The problem is that I have to query without MIBs.

Thanks for the fast response,

Andreas
