### ISSUE TITLE
Snmptable request

### ISSUE THREAD

**Issue by ssoto** [vincentbernat/snimpy#32]
Hi all.
First of all congratulations about yout work. This module likes very good.

After many time trying to use Collectd, tcollector, etc We decide make our own network analizer based on SNMP. I made the mistake do it on my own, parsing `snmp table` line command output inside of use an existing module that supports `snmptable` operation.

I would like your advice about using `snimpy` to make request about `snmptable` OIDs.

The class who make the request is:
https://github.com/wtelecom/net-interviewer/blob/master/src/snmp/table.py#L10

Regards!

**Comment by vincentbernat** [comment]
With Snimpy, you can't query a table. You will need to query individual rows. This may be a bit less efficient but when enabling caching, this should do the same. See the example on the homepage:

```python
    load("IP-FORWARD-MIB")
    m=M("localhost", "public", 2)
    routes = m.ipCidrRouteNextHop
    for x in routes:
        net, netmask, tos, src = x
        print("%15s/%-15s via %-15s src %-15s" % (net, netmask, routes[x], src))
```

**Comment by vincentbernat** [comment]
If you need more flexibility, you can also use pysnmp directly. There is some high level modules to do that easily.

**Comment by ssoto** [comment]
Thank you so much for your fast reply @vincentbernat !

I will study `pysnmp` to use it
