### ISSUE TITLE
Two different MIBs with the same scalar name

### ISSUE THREAD

**Issue by rminsk** [vincentbernat/snimpy#36]
I have two different MIBs with the same scalar name that I need to load.  Is there a way to prefix the scalar name with the module name?

We have a.mib and b.mib and they both have the scalar 'foo'.  What would happen if we do
snimpy.manager.load('a.mib') followed by snimpy.manager.load('b.mib')?  What would happen if I loaded them in the other order?  Could you add manager['A-MIB::foo']?  Or manager['A-MIB'].foo?

**Comment by vincentbernat** [comment]
The second syntax would be possible to implement. I'll try to do that.

**Comment by vincentbernat** [comment]
I have implemented the second syntax you proposed. Please, try.

**Comment by rminsk** [comment]
Seems to be working.  A side effect is a small optimization if you are accessing lots of scalars from the same module.  You can limit to searching only oids in the single module.

restricted_manager = manager['A-MIB']
restricted_manager.foo = 1
print restricted_manager.bar
...
