### ISSUE TITLE
How to index table with two indexes?

### ISSUE THREAD

**Issue by rminsk** [vincentbernat/snimpy#37]
The following mib has two indexes "INDEX { cpuUtilizationCnIndex, cpuIndex }".  How do I dereference on both indexes?

    cpuUtilizationNumber OBJECT-TYPE
        SYNTAX Integer32
        MAX-ACCESS read-only
        STATUS current
        DESCRIPTION
            "The number of CPUs which may be present on this
             system."
        ::= { utilization 1 }

    cpuUtilizationTable OBJECT-TYPE
        SYNTAX SEQUENCE OF CpuUtilizationEntry
        MAX-ACCESS not-accessible
        STATUS current
        DESCRIPTION
            "A table of usage information relevant to each CPU
             which may be present on this system.

             The number of entries in this table is given by the value
             of cpuUtilizationNumber."
        ::= { utilization 2 }

    cpuUtilizationEntry OBJECT-TYPE
        SYNTAX CpuUtilizationEntry
        MAX-ACCESS not-accessible
        STATUS current
        DESCRIPTION
            "Usage information for a CPU which may be
             present on this system."
        INDEX { cpuUtilizationCnIndex, cpuIndex }
        ::= { cpuUtilizationTable 1 }

    CpuUtilizationEntry ::=
        SEQUENCE {
            cpuUtilizationCnIndex
                Unsigned32,
            cpuIndex
                Unsigned32,
            cpuUtilization
                Unsigned32
        }

    cpuUtilizationCnIndex OBJECT-TYPE
        SYNTAX Unsigned32 (1..255)
        MAX-ACCESS read-only
        STATUS current
        DESCRIPTION
            "The cluster node for this value."
        ::= { cpuUtilizationEntry 1 }

    cpuIndex OBJECT-TYPE
        SYNTAX Unsigned32
        MAX-ACCESS read-only
        STATUS current
        DESCRIPTION
            "CPU core index."
        ::= { cpuUtilizationEntry 2 }

    cpuUtilization OBJECT-TYPE
        SYNTAX Unsigned32
        MAX-ACCESS read-only
        STATUS current
        DESCRIPTION
            "Current percentage usage of this CPU."
        ::= { cpuUtilizationEntry 3 }

BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.1.0 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.1.1 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.1.2 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.1.3 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.2.0 = Gauge32: 2
BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.2.1 = Gauge32: 2
BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.2.2 = Gauge32: 2
BLUEARC-SERVER-MIB::cpuUtilizationCnIndex.2.3 = Gauge32: 2
BLUEARC-SERVER-MIB::cpuIndex.1.0 = Gauge32: 0
BLUEARC-SERVER-MIB::cpuIndex.1.1 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuIndex.1.2 = Gauge32: 2
BLUEARC-SERVER-MIB::cpuIndex.1.3 = Gauge32: 3
BLUEARC-SERVER-MIB::cpuIndex.2.0 = Gauge32: 0
BLUEARC-SERVER-MIB::cpuIndex.2.1 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuIndex.2.2 = Gauge32: 2
BLUEARC-SERVER-MIB::cpuIndex.2.3 = Gauge32: 3
BLUEARC-SERVER-MIB::cpuUtilization.1.0 = Gauge32: 0
BLUEARC-SERVER-MIB::cpuUtilization.1.1 = Gauge32: 3
BLUEARC-SERVER-MIB::cpuUtilization.1.2 = Gauge32: 0
BLUEARC-SERVER-MIB::cpuUtilization.1.3 = Gauge32: 0
BLUEARC-SERVER-MIB::cpuUtilization.2.0 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuUtilization.2.1 = Gauge32: 1
BLUEARC-SERVER-MIB::cpuUtilization.2.2 = Gauge32: 0
BLUEARC-SERVER-MIB::cpuUtilization.2.3 = Gauge32: 0

**Comment by vincentbernat** [comment]
For example:

```python
m.cpuUtilization[2,3]
```

Or to iterate:

```python
for node, cpu in m.cpuUtilization:
    print m.cpuUtilization[node, cpu]
```
