### ISSUE TITLE
Need to be able to configure bulk value on init

### ISSUE THREAD

**Issue by jejenone** [vincentbernat/snimpy#38]
I have a use case where I'd need to be able to set the bulk value (hardcoded to 40 today) to something else.
Setting it afterwards does not seem to work.
Is that possible ?
Thanks.

**Comment by vincentbernat** [comment]
The manager now accepts a `bulk` parameter you can set to `0` or any other value. However, setting it afterwards (on the session object) should have worked too.

**Comment by jejenone** [comment]
When I tried setting it afterwards, I could still the next bulk requests with a repeat of 40 (using tcpdump)

thanks a lot for the commit!
