### ISSUE TITLE
Benchmark comparison: Snimpy vs netsnmp

### ISSUE THREAD

**Issue by kamakazikamikaze** [vincentbernat/snimpy#39]
We've been using the `netsnmp` package for a while in collecting data from our network devices. Unfortunately, due to the lack of a `BULKWALK` implementation and the significant memory leak we've found with the `WALK` implementation we've had to look to alternatives. `fastsnmpy` was the first adapter/extension/package we came across that did well to fetch data we needed. However, the  `BULKWALK` implementation would sometimes skip the first OID. I've attempted, thus far unsuccessfully, to [modify it myself](https://github.com/kamakazikamikaze/fastsnmpy) but I cannot seem to get it to behave properly. Thankfully `snimpy` has made the process much easier

One concern we have is with the performance of `snimpy`. We've completed a cloned script that replaces `fastsnmpy` with `snimpy` with success and compared it to the older implementation. Unfortunately we have found that `snimpy` runs at half the speed of `fastsnmpy`. I am not 100% certain if this is due to how we implemented it or if this is to be expected.

## Statistics
________

**Devices being polled:** 2,693
**Values being accessed per device:** varies, 4 to 64 
Each device being queried is done immediately one after the other.
Script goes through all devices then sleeps for 5 minutes before looping again.
Script runs 24/7

#### Timed Results
`fastsnmpy` : averages 124 seconds
`snimpy` : averages 242 seconds

##### Memory footprint:
`fastsnmpy WALK`: 30MB for first loop, adds 10MB for every loop thereafter (yikes!!)
`fastsnmpy GETBULK`: 40MB avg. throughout full runtime
`snimpy` : 45MB avg. throughout full runtime

_____________

###### With `snimpy`

```Python
def Query(self, arrays, community_str):
		responded = {}									# Valid Arrays, used for ZIP
		doc_uploaded = 0
		doc_failed = 0
		for array in arrays:					
			try:
				session = M(array, community_str, timeout = 2, retries = 1, cache = True)
				antennas = {}
				model = str(session.arrayModel)
				ip = str(session.ethIPAddress[1])
				slots = 0
				for ant in session.iapType:
					slots = ant							
					if session.iapPresent[ant] and not session.iapDot11Mode[ant] == 2:					
						antennas[ant] = session.iapNumStations[ant]			
				responded[array] = {'model' : model, 'ip' : ip, 'antennas' : antennas, 'radioSlots' : slots}
				#del session
				#del antennas
			except:					# Host is not found. Quick alternative to a PING
				continue
			. . .
```

###### Using `fastsnmpy` 
(method `seqwalk()` is essentially just `netsnmp.Session.walk()`)
```Python
def Query(self, arrays, community_str, var):	# `var` is a List of OIDs to target. We have only three for this script
		session = SnmpSession ( timeout = 1000000 ,
				retries = 1,
				verbose = self.verbose,
				oidlist = var,
				targets = arrays, 
				community = community_str
				)
				
		#results = session.bulkwalk()		# Sometimes omits the first value/OID returned. I'll debug this myself in the future
		results = session.seqwalk()		# Finished.
		del session
		
		last_host = None
		hosts = []              				  # the list of hosts
		host_responses = []     			  # the list of responses for each host
		responses = []
		for output in results:
			if output.val is not None:
				if output.hostname != last_host:   		 # new host
					if last_host:    # only append host_responses after a new host
						host_responses.append(responses)
					hosts.append(output.hostname)
					responses = [output.val]       		 # start the new list of responses
					last_host = output.hostname
				else:                              				 # same host, append the response
					responses.append(output.val)
			. . .
```

If there's something I'm doing wrong I would greatly appreciate the feedback, however I must insist that you attempt to benchmark something similar and compare it with `netsnmp`. I am of the opinion that `snimpy` can perform faster than this.

**Comment by vincentbernat** [comment]
❦ 19 août 2015 18:15 -0700, Kent Coble <notifications@github.com> :

> We've been using the netsnmp package for a while in collecting data
> from our network devices. Unfortunately, due to the lack of a BULKWALK
> implementation and the significant memory leak we've found with the
> WALK implementation we've had to look to alternatives. fastsnmpy was
> the first adapter/extension/package we came across that did well to
> fetch data we needed. However, the BULKWALK implementation would
> sometimes skip the first OID. I've attempted, thus far unsuccessfully,
> to modify it myself but I cannot seem to get it to behave properly.
> Thankfully snimpy has made the process much easier
>
> One concern we have is with the performance of snimpy. We've completed
> a cloned script that replaces fastsnmpy with snimpy with success and
> compared it to the older implementation. Unfortunately we have found
> that snimpy runs at half the speed of fastsnmpy. I am not 100% certain
> if this is due to how we implemented it or if this is to be expected.

It is a bit expected. Snimpy does a lot of additional work with the
returned results to look more Pythonic. Maybe have a look at EasySNMP
which uses NetSNMP C API.
-- 
Don't use conditional branches as a substitute for a logical expression.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by vincentbernat** [comment]
Also, maybe fastsnmpy is using several threads to query your array of hosts. This should be possible with Snimpy too. What is the typical size of `arrays`?

**Comment by kamakazikamikaze** [comment]
Fastsnmpy isn't utilizing multithreading. While the option exists via `multiwalk()` it doesn't cap the number of threads it spawns. With 2,700 devices it becomes very, very taxing upon the system.

`arrays` is one of three rough sizes: 70; 1,270; 1,300. I'm currently pursuing a way of breaking these down into smaller groups and threading them but I've never used threading.

Would it be faster with `snimpy` to assign the branch of values that I need to access into a temporary variable? Ex. instead of `for ant in session.iapType:` do `antennas = session.iapType; for antenna in antennas`? I'm not entirely certain if the former causes individual requests or if it's already retrieved and saved. I found no performance difference between enabling and disabling `cache`

**Comment by vincentbernat** [comment]
❦ 20 août 2015 05:01 -0700, Kent Coble <notifications@github.com> :

> Would it be faster with snimpy to assign the branch of values that I
> need to access into a temporary variable? Ex. instead of for ant in
> session.iapType: do antennas = session.iapType; for antenna in
> antennas? I'm not entirely certain if the former causes individual
> requests or if it's already retrieved and saved. I found no
> performance difference between enabling and disabling cache

It would be exactly the same. The cache helps a lot because it avoids
sending SNMP GET for OID that have already been walked.

What may also help is to loop over session.iapPresent,
session.iapDot11Mode and others with cache enabled. This way, those
values are retrieved with bulk walk instead of individual GET.

    for ant in session.iapPresent:
        pass
    for ant in session.iapDot11Mode:
        pass
    ...
-- 
Don't stop at one bug.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by kamakazikamikaze** [comment]
> What may also help is to loop over session.iapPresent,
session.iapDot11Mode and others with cache enabled. This way, those
values are retrieved with bulk walk instead of individual GET.

I'll try that out.

Also, I looked into `easysnmp` which looks promising but currently lacks a `BULKWALK` implementation. I'll try that and see what the performance difference is, however I must applaud your project for the simple, Pythonic interface it offers compared to other packages that are out there

**Comment by kamakazikamikaze** [comment]
You can close this. I tried a few `threading`/`multiprocessing` implementations but they couldn't meet our needs for this specific project. We'll keep using `Snimpy` in smaller projects due to the more Pythonic implementation and impressively minimal memory leaks.

**Comment by vincentbernat** [comment]
OK!
