### ISSUE TITLE
Calling type on a table node segfaults in snimpy.mib

### ISSUE THREAD

**Issue by nward** [vincentbernat/snimpy#44]
Hi,

I'm attempting to use snimpy's MIB parsing stuff, as pysnmp's seems like it's got a bit of a steep learning curve.

The following causes a segfault of snimpy 0.8.6 on both OS X (python 2.7.6) and Linux (python 2.7.10). libsmi 0.4.8 on both.

```
import snimpy.mib
snimpy.mib.load('SNMPv2-SMI')
snimpy.mib.load('IF-MIB')
a = snimpy.mib.get('IF-MIB', 'ifTable')
a.type
```

I suspect this isn't desired behaviour, or if type() isn't appropriate to call here, perhaps we should have a guard condition to prevent it segfaulting?

**Comment by vincentbernat** [comment]
I'll raise an exception in case there is no type we can solve to.

Note however that type handling is considered to be an internal detail of Snimpy. Snimpy is only about the high-level interface. I would prefer to have no user of those low level interfaces but I understand that there is currently not much alternatives.
