### ISSUE TITLE
Slight inconsistency with partial indexes

### ISSUE THREAD

**Issue by unikmhz** [vincentbernat/snimpy#50]
Hello again.

There is a slight inconsistency with my previous PR - using ```iteritems()``` iterates over index-value pairs, and using subscript syntax ```[]``` iterates over indexes only. Although this behaviour is consistent with existing ```snimpy``` syntax, this is not reflected in the docs.

I can create a new PR addressing this in one of the following ways:

1. Patch documentation to reflect this fact. This is ok; the only nitpick that python coders don't generally think of ```iteritems()``` as accepting an argument.
2. Modify subscript with partial indexes to behave like original ```iteritems()``` - iterating over index-value pairs. This can work, but is inconsistent with using "normal" (non-subscripted) syntax, which iterates over indexes only.

Can you advise on which way should I go, or suggest an alternative solution? Thanks, and sorry to bother you.

**Comment by vincentbernat** [comment]
I would prefer the first solution as this is more natural (even if less efficient when you need to also get values).

**Comment by vincentbernat** [comment]
About `iteritems()`, you could also do `somestuff[10].iteritems()` by returning a `ProxyColumn` instance and make `ProxyColumn` able to handle a partial index. It would also enable things like `somestuff[10][5][3]`. I think that would be nice to have.
