### ISSUE TITLE
get session from manager

### ISSUE THREAD

**Issue by cbueche** [vincentbernat/snimpy#62]
This is not really an issue but more a question: if I create a manager using something like this `m = M(host=devicename, community=...)` but I need the session to do a `session.get()` or `session.walkmore()`, how can I recover it ?

I'm using `session = m._session._session` but it looks a bit ugly to me. Any advice ?

**Comment by vincentbernat** [comment]
I don't see why you would need to have `_session._session`. But otherwise, no, there is no better way.

**Comment by cbueche** [comment]
Thank you Vincent for your quick answer, I should have explained me better. The reason is, (within [Agent-Jones](https://github.com/cbueche/Agent-Jones)) for 99% of my SNMP get and set, I use MIBs and the pythonic interface:

`for index, operstatus in m.ifOperStatus.iteritems():
    use(index & operstatus)`

but in one place, I want to allow a SNMP get/walk on an oid passed as parameter :

`http://url/aj/api/v1/oidpump/192.168.20.60/get/1.3.6.1.2.1.1.3.0
http://url/aj/api/v1/oidpump/192.168.20.60/walk/1.3.6.1.2.1.31.1.1.1.1`

Or Is there a way to do this using a manager ?

**Comment by vincentbernat** [comment]
That's not possible with the manager. So, your way of doing it is the better way. I don't want to provide an "official" way because it would mean that I have to maintain some stability guarantee on the session API. I didn't intend for people to use it (but many do).

**Comment by cbueche** [comment]
That's ok, I can live with this workaround. Thanks again for your support !
