### ISSUE TITLE
SNMPv3 contextName

### ISSUE THREAD

**Issue by johnworkman** [vincentbernat/snimpy#65]
Is it possible to specify a specific SNMPv3 contextName, for example, snmpwalk -n vlan-713 ?

**Comment by vincentbernat** [comment]
It's currently not possible, but it seems easy to add.

**Comment by vincentbernat** [comment]
Could you test PR #66?

**Comment by johnworkman** [comment]
That seems to work perfectly and is extremely helpful to me. Thank you!
