### ISSUE TITLE
SNMP socket is leaked

### ISSUE THREAD

**Issue by iwanb** [vincentbernat/snimpy#75]
Creating and deleting a Manager leaves an UDP socket open, even if I run the garbage collector.
It seems the leak comes from PySNMP, but I do not know if it is a bug or some clean up function should be called.

Doing `manager._session._transport.transport.closeTransport()` closes the socket. Maybe this should be exposed in the manager object? Or is there a better way to clean up PySNMP open sockets?

The open sockets can be seen with `lsof` or the `psutil` python package.

**Comment by vincentbernat** [comment]
How do you "delete" a manager? A minimal example would help. If we need to call `closeTransport()`, we are likely to be able to do it without involving the user. BTW, which version of PySNMP? SNMPv2 or SNMPv3?

**Comment by iwanb** [comment]
True, I meant delete as let the object out of scope or delete the variable:
```
from snimpy.manager import Manager, load
import gc
import weakref
load('SNMPv2-MIB')
m = Manager(hostname)
r = weakref(m)
# Make sure the socket is opened
m.sysContact
# Cleanup
del m
gc.collect()
assert r() is None # Manager is deleted
# socket is still there
```

I use SNMPv2 with PySNMP 4.3.9.

**Comment by vincentbernat** [comment]
If I repeat the operation several times, it seems that PySNMP is keeping the same socket for everything. Do you make the same observation? In this case, this is not really a leak:

```
from snimpy.manager import Manager, load
import gc
import weakref
load('SNMPv2-MIB')
for i in range(10):
    m = Manager('localhost')
    r = weakref.ref(m)
    # Make sure the socket is opened
    m.sysContact
    # Cleanup
    del m
    gc.collect()
    assert r() is None # Manager is deleted
```

**Comment by iwanb** [comment]
Indeed you are right, then you do not want to close it as it could break another manager.

I still wonder if there is a recommended way to clean it up, I will look at the PySNMP side.

Thank you for checking !

**Comment by vincentbernat** [comment]
I'll close this issue then.
