### ISSUE TITLE
How do I get by OID

### ISSUE THREAD

**Issue by gavmckee80** [vincentbernat/snimpy#78]
How do I get retrieve a value directly from its OID

```
host = 1.1.1.1
community = public
oid = .1.3.6.1.2.1.47.1.1.1.1.11.1 
(OID is Arista serial number)
```

**Comment by vincentbernat** [comment]
This is not something Snimpy is designed for. You can use the lower level API (they are in the documentation), but maybe you should use another Python binding if you want to use OID. With Snimpy, you should load the MIB.

**Comment by gavmckee80** [comment]
@vincentbernat thanks
