### ISSUE TITLE
How to get  KEEPALIVED-MIB::vrrpSyncGroupState

### ISSUE THREAD

**Issue by 3c2b2ff5** [vincentbernat/snimpy#87]
Hi,

with snmpwalk I can get `KEEPALIVED-MIB::vrrpSyncGroupState`:
```
# snmpwalk -v2c -cpublic localhost KEEPALIVED-MIB::vrrpSyncGroupState
KEEPALIVED-MIB::vrrpSyncGroupState.1 = INTEGER: backup(1)
```
How can I get it to work with snimpy, I have tried the following:
```
#!/usr/bin/env python3

from snimpy.manager import Manager as M
from snimpy.manager import load
import sys

try:
    load("KEEPALIVED-MIB::vrrpSyncGroupState")
    #load("KEEPALIVED-MIB::keepalived")
    #load("KEEPALIVED-MIB::vrrp")
    #load("KEEPALIVED-MIB")
    m = M(host='localhost', community='public', version=2)
    print(m.vrrpOperState)
except Exception as e:
    print(e)
```
I always get the exception what ever I `load`.
```
unable to find b'KEEPALIVED-MIB::vrrpSyncGroupState' (check the path)
```
Isn't `vrrpSyncGroupState` part of `vrrp_instance`? or do I miss something here?

Thanks a lot

**Comment by vincentbernat** [comment]
You need to load `KEEPALIVED-MIB`. What do you get when you try to load it?

**Comment by 3c2b2ff5** [comment]
Hi Vincent,

I get the following error:
```
SMIException("unable to find b'KEEPALIVED-MIB' (check the path)",))
```

**Comment by vincentbernat** [comment]
Try to give the full path to the MIB instead.

**Comment by 3c2b2ff5** [comment]
```
#!/usr/bin/env python3

from snimpy.manager import Manager as M
from snimpy.manager import load
import sys

try:
    load('KEEPALIVED-MIB::vrrpSyncGroupState.1')
except Exception as e:
    print(e)
```
I still get the exception:
```
    SMIException("unable to find b'KEEPALIVED-MIB::vrrpSyncGroupState.1' (check the path)",))

**Comment by vincentbernat** [comment]
The MIB is a file. If it is not in the current directory or in the search path, you need to load the full path, like `load('/path/to/KEEPALIVED-MIB')`.

**Comment by 3c2b2ff5** [comment]
It works. But I am really, since I have ` VRRP-MIB` in `/usr/share/snmp/mibs/VRRP-MIB.txt` and `/var/lib/mibs/ietf/VRRP-MIB`, but `KEEPALIVED-MIB` exists only in `/usr/share/snmp/mibs/KEEPALIVED.txt`. I never realized that.

Thank you very much.

**Comment by vincentbernat** [comment]
The search path can be tweaked in `/etc/smi.conf`.

**Comment by 3c2b2ff5** [comment]
Well, loading `/usr/share/snmp/mibs/KEEPALIVED-MIB.txt` was successful, so I assume yes it can.
