### ISSUE TITLE
Confusing example in documentation

### ISSUE THREAD

**Issue by david672orford** [vincentbernat/snimpy#95]
https://snimpy.readthedocs.io/en/latest/usage.html

In the example interactive session we are shown how to load MIB-IF, create a manager, and retrieve sysDesc. This fails because sysDescr is from SNMPv2-MIB, not MIB-IF. The exception is:

    AttributeError: sysDescr is not an attribute

This error message is very generic. I had to dig into the code to figure out what it meant. It then took more digging around in my system's MIB files to discover that sysDesc is in a different MIB than the one suggested.

Suggest two fixes:
* Load SNMPv2-MIB in the example
* Make the error message more explicit, perhaps "%s not found in MIBs"

**Comment by vincentbernat** [comment]
Done. Thanks!
