### ISSUE TITLE
Deprecation warning: snimpy not compatible with upcoming Python 3.10

### ISSUE THREAD

**Issue by jcass77** [vincentbernat/snimpy#97]
[This line](https://github.com/vincentbernat/snimpy/blob/f58f2a0266674cdef976149db8600e5bba6e5f98/snimpy/manager.py#L33) in manager.py causes a deprecation warning:

>site-packages/snimpy/manager.py:34: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working from collections import MutableMapping, Container, Iterable, Sized

**Comment by vincentbernat** [comment]
Hello,

Not sure to understand, the line is already correct. The import is done
from `collections.abc`, not from `collections` and this is the right
thing to do.

**Comment by vincentbernat** [comment]
In case you did install with `pip`, I have uploaded 1.0.0 that should fix the issue you were seeing. This version drops compatibility with Python 2.
